document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"zh-cn\">");
document.writeln("<head>");
document.writeln("  <meta charset=\"utf-8\">");
document.writeln("  <title>Mamer论坛</title>");
document.writeln("  <style>");
document.writeln("    *{");
document.writeln("      font-family: 微软雅黑；");
document.writeln("    }");
document.writeln("  </style>");
document.writeln("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">");
document.writeln("  <script type=\"text/javascript\" src=\"js/jQuery.min.js\"></script>");
document.writeln("  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>");
document.writeln("  <script type=\"text/javascript\" src=\"js/holder.min.js\"></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  <div class=\"container\">");
document.writeln("    <h1 class=\"page-header\">Mamer论坛</h1>");
document.writeln("    <nav class=\"navbar navbar-default\">");
document.writeln("            <div class=\"navbar-header\">");
document.writeln("                <a href=\"#\" class=\"navbar-brand\">首页</a>");
document.writeln("                <button class=\"navbar-toggle collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#mynavbar\">");
document.writeln("               <!--窗口缩小后出现-->");
document.writeln("              <span class=\"icon-bar\"></span>");
document.writeln("              <span class=\"icon-bar\"></span>");
document.writeln("              <span class=\"icon-bar\"></span>");
document.writeln("              </button>");
document.writeln("            </div>");
document.writeln("            <div id=\"mynavbar\" class=\"collapse navbar-collapse\">");
document.writeln("                <ul class=\"nav navbar-nav\">");
document.writeln("                    <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">话题</a></li> ");
document.writeln("                    <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">分享</a></li>");
document.writeln("                    <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">教程</a></li>");
document.writeln("                    <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">问答</a></li>     ");
document.writeln("                    <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">公告</a></li>");
document.writeln("                </ul>");
document.writeln("                <ul class=\"nav navbar-nav navbar-right\" >");
document.writeln("                  <li class=\"nav-item\"><a href=\"./login.html\" class=\"nav-link\">登陆</a></li>");
document.writeln("                  <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">注册</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("");
document.writeln("");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");